// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:cec2aede-7f25-463d-9671-dd6edf08a9be",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_iUnJCan2s",
    "aws_user_pools_web_client_id": "766j4if844o95msj8r9br1f43e",
    "oauth": {},
    "aws_user_files_s3_bucket": "pds-details152001-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://xxlixecgxfe3zohzeftoqu5msi.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "externalApi-dev",
            "endpoint": "https://kg2sihwrv7.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        },
        {
            "name": "ddsApi-dev",
            "endpoint": "https://216j3p1j6g.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        }
    ],
    "aws_content_delivery_bucket": "pdsui-20200204165401-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d3ct464w1g9eg3.cloudfront.net"
};


export default awsmobile;
