import { I18n } from 'aws-amplify';

const dict = {
    'ja': {
        // 'Account recovery requires verified contact information': 'アカウントの復旧には、確認済みの連絡先情報が必要です',
        'Back to Sign In': 'サインイン画面に戻る',
        'Confirm': '確認',
        'Confirm Sign Up': 'サインアップの確認',
        'Confirmation Code': '確認コード',
        'Create Account': '新規登録',
        'Create a new account': 'アカウントの新規登録',
        'Create account': '新規登録',
        'Code': 'コード',
        'Confirm SMS Code': 'SMS確認コード',
        'Email': 'メールアドレス',
        'Enter your code': '確認コードを入力してください。',
        'Enter your password': 'パスワードを入力してください。',
        'Enter your username': 'ユーザー名を入力してください。',
        'Enter your phone number': '電話番号を入力してください。',
        'Enter your email': 'メールアドレスを入力してください。',
        'Forget your password? ': 'パスワードをお忘れの方 ',
        'Have an account? ': 'アカウント登録済みの方',
        'Hello': 'こんにちは ',
        'Incorrect username or password': 'ユーザー名またはパスワードが間違っています。',
        'Lost your code? ': 'コードを紛失した方 ',
        'No account? ': 'アカウント未登録の方 ',
        'New Password': '新しいパスワード',
        'Password': 'パスワード',
        'Phone Number': '電話番号',
        'Resend Code': '確認コードの再送',
        'Reset password': 'パスワードのリセット',
        'Reset your password': 'パスワードのリセット',
        'Send Code': 'コードの送信',
        'Sign In': 'サインイン',
        'Sign Out': 'サインアウト',
        'Sign in': 'サインイン',
        'Sign in to your account': 'PDSサービス',
        'Submit': '送信',
        'Skip': 'スキップ',
        'User does not exist': 'ユーザー名またはパスワードが間違っています。',
        'Username': 'ユーザー名',
        'Username cannot be empty': 'ユーザー名を入力ください。',
        'Username/client id combination not found.': 'ユーザーは存在しません。',
        'Select a Photo': 'ファイルを選択してください。',
        'Pick': 'ファイルを選択してください。',
        'Change Password': 'パスワード変更',
        'Change': '変更する',
        'Verify':'認証',
        'Password did not conform with policy: Password not long enough': 'パスワードは8桁数以上を入力してください。',
        'Custom auth lambda trigger is not configured for the user pool.': 'パスワードを入力ください。',
        'Invalid email address format.': '正しいメールアドレスを入力してください。',
        'Confirmation code cannot be empty': '確認コードを入力してくだい。',
        'The following fields need to be filled out: Username': 'ユーザー名を入力してください。',
        'The following fields need to be filled out: Password': 'パスワードを入力してください。',
        'The following fields need to be filled out: Email': 'メールアドレスを入力ください。',
        'The following fields need to be filled out: Password, Email': 'パスワード、メールアドレスを入力してください。',
        'The following fields need to be filled out: Username, Email': 'ユーザー名、メールアドレスを入力してください。',
        'The following fields need to be filled out: Username, Password': 'ユーザー名、パスワードを入力してください。',
        'The following fields need to be filled out: Username, Password, Email': 'ユーザー名、パスワード、メールアドレスを入力してください。',
        'Invalid verification code provided, please try again.': '確認コードが間違っています。',
        'Invalid phone number format. Please use a phone number format of +12345678900': '正しい電話を入力してください。',
        'Account recovery requires verified contact information': 'アカウントの復旧には連絡先情報認証が必要です。',
        'User already exists': '該当ユーザー既に存在しています。',
        'Invalid password format': 'パスワードの形式は間違っています。',
        'Password cannot be empty': '新しいパスワードを入力してください。'
    }
};

I18n.setLanguage('ja');
I18n.putVocabularies(dict);
